### ISSUE TITLE
Missing cover

### ISSUE THREAD

**Issue by sethwoodworth** [GITenberg/A-Tale-of-Two-Cities_98#2]
Cover.jpg contains 404 html

**Comment by rdhyee** [comment]
Thanks, @sethwoodworth -- problem fixed with https://github.com/GITenberg/A-Tale-of-Two-Cities_98/commit/d3f6f2f3b8e3f218f8bf5a2194f385ea9a37ca9e.

The issue stems from an incorrect filename in https://github.com/plympton/rtc/blob/master/books.json --> I've issued https://github.com/plympton/rtc/pull/2.
